apiVersion: v1
kind: Secret
metadata:
  name: rag-grafana-secret
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-grafana
  template:
    metadata:
      labels:
        app: rag-grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:11.3.1
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: rag-grafana-secret
---
apiVersion: v1
kind: Service
metadata:
  name: rag-grafana
spec:
  selector:
    app: rag-grafana
  ports:
    - port: 3000
      targetPort: 3000
