global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "rag-platform-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:3000"]
        labels:
          service: api

  - job_name: "rag-platform-orchestrator"
    metrics_path: /metrics
    static_configs:
      - targets: ["orchestrator:3001"]
        labels:
          service: orchestrator
