export enum OmnichannelMessageStatus {
  RECEIVED = "RECEIVED",
  NORMALIZED = "NORMALIZED",
  PROCESSING = "PROCESSING",
  PROCESSED = "PROCESSED",
  FAILED = "FAILED",
  DISPATCHED = "DISPATCHED",
}
