apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - web-deployment.yaml
  - web-service.yaml
  - api-web-deployment.yaml
  - api-web-service.yaml
  - api-business-deployment.yaml
  - api-business-service.yaml
  - orchestrator-deployment.yaml
  - orchestrator-service.yaml
  - api-web-hpa.yaml
  - api-business-hpa.yaml
  - orchestrator-hpa.yaml
  - ingress.yaml
