apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-platform-dev

resources:
  - ../../base
  - namespace.yaml

patchesStrategicMerge:
  - ingress-patch.yaml
  - web-replicas-patch.yaml
  - api-web-replicas-patch.yaml
  - api-business-replicas-patch.yaml
  - orchestrator-replicas-patch.yaml
  - api-web-hpa-patch.yaml
  - api-business-hpa-patch.yaml
  - orchestrator-hpa-patch.yaml
