name: deploy-prod

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-prod
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Infrastructure - Prod
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      TF_IN_AUTOMATION: "true"
    defaults:
      run:
        working-directory: infra/terraform/envs/prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/api-business/Dockerfile
          push: false
          tags: rag-platform-api-business:prod

      - name: Build API Web image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/api-web/Dockerfile
          push: false
          tags: rag-platform-api-web:prod

      - name: Build orchestrator image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/orchestrator/Dockerfile
          push: false
          tags: rag-platform-orchestrator:prod

      - name: Build web image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/web/Dockerfile
          push: false
          tags: rag-platform-web:prod

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -var-file=terraform.tfvars -out=tfplan

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
